language: generic

sudo: false
dist: trusty


cache:
    directories:
        - ${TRAVIS_BUILD_DIR}/deps/cmake

matrix:
    include:
    - env: CXX=g++-7 CC=gcc-7
      addons:
        apt:
          packages:
            - g++-7
            - valgrind
          sources: &sources
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise
            - llvm-toolchain-precise-3.9
            - llvm-toolchain-precise-3.8
            - llvm-toolchain-precise-3.7
            - llvm-toolchain-precise-3.6
            - sourceline: 'deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty-4.0 main'
              key_url: 'http://apt.llvm.org/llvm-snapshot.gpg.key'
    - env: CXX=g++-6 CC=gcc-6 EXTRA_CMAKE=-DDEFLATE_SUPPORT=Off
      addons:
        apt:
          packages:
            - g++-6
            - valgrind
          sources: *sources
    - env: CXX=g++-6 CC=gcc-6
      addons:
        apt:
          packages:
            - g++-6
            - valgrind
          sources: *sources
    - env: CXX=g++-5 CC=gcc-5
      addons:
        apt:
          packages:
            - g++-5
            - valgrind
          sources: *sources
    - env: CXX=g++-4.9 CC=gcc-4.9
      addons:
        apt:
          packages:
            - g++-4.9
            - valgrind
          sources: *sources
    - env: CXX=g++-4.8 CC=gcc-4.8
      addons:
        apt:
          packages:
            - g++-4.8
            - valgrind
          sources: *sources
    - env: CXX=g++-4.7 CC=gcc-4.7
      addons:
        apt:
          packages:
            - g++-4.7
            - valgrind
          sources: *sources
    - env: CXX=clang++-4.0 CC=clang-4.0
      addons:
        apt:
          packages:
            - clang-4.0
            - libc++-dev
            - valgrind
          sources: *sources
    - env: CXX=clang++-3.9 CC=clang-3.9
      addons:
        apt:
          packages:
            - clang-3.9
            - libc++-dev
            - valgrind
          sources: *sources
    - env: CXX=clang++-3.8 CC=clang-3.8
      addons:
        apt:
          packages:
            - clang-3.8
            - libc++-dev
            - valgrind
          sources: *sources
    - env: CXX=clang++-3.7 CC=clang-3.7
      addons:
        apt:
          packages:
            - clang-3.7
            - libc++-dev
            - valgrind
          sources: *sources
    - env: CXX=clang++-3.6 CC=clang-3.6
      addons:
        apt:
          packages:
            - clang-3.6
            - libc++-dev
            - valgrind
          sources: *sources

install:
    - if [[ "$CXX" == clang* ]]; then export CXXFLAGS="-stdlib=libc++"; fi
    - JOBS=2
    - DEPS_DIR="${TRAVIS_BUILD_DIR}/deps"
    - mkdir -p "${DEPS_DIR}" && cd "${DEPS_DIR}"
    - |
      if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
        if [[ ! -d "$(ls -A ${DEPS_DIR}/cmake)" ]]; then
          CMAKE_URL="https://cmake.org/files/v3.6/cmake-3.6.2-Linux-x86_64.tar.gz"
          mkdir -p cmake && travis_retry wget --no-check-certificate --quiet -O - "${CMAKE_URL}" | tar --strip-components=1 -xz -C cmake
        fi
        export PATH="${DEPS_DIR}/cmake/bin:${PATH}"
      else
        if ! brew ls --version cmake &>/dev/null; then brew install cmake; fi
      fi

before_script:
    - cd "${TRAVIS_BUILD_DIR}"
    - cmake --version
    - cmake . -Bbuild -DCMAKE_BUILD_TYPE=Release ${EXTRA_CMAKE}
    - cmake --build build -- -j${JOBS}

script:
    - cd build
    - ctest -D ExperimentalBuild -j${JOBS}
    - ctest -D ExperimentalMemCheck -j${JOBS}
